<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>KoenZomers.UniFi.Api</AssemblyName>
    <RootNamespace>KoenZomers.UniFi.Api</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>
    <Version>2.3.1.0</Version>
    <Authors>Koen Zomers</Authors>
    <Company>Koen Zomers</Company>
    <Description>API in .NET 10 to fetch data from an on premises Ubiquiti UniFi Controller</Description>
    <Copyright>Koen Zomers</Copyright>
    <PackageProjectUrl>https://github.com/KoenZomers/UniFiApi</PackageProjectUrl>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <PackageReleaseNotes>- Updated to .NET 10
- Added PUT request support
- Added methods to manage PoE port overrides and power cycle commands</PackageReleaseNotes>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>KoenZomers.UniFi.Api.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <DocumentationFile>KoenZomers.UniFi.Api.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
    <IsAotCompatible>False</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
    <IsAotCompatible>False</IsAotCompatible>
  </PropertyGroup>

</Project>
